---
title: "Introduction to R"
subtitle: "Session 1: Terminology"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

## This Session

In this session we will focus on getting started on data analysis using Posit Workbench. By the end of this session, you will have the knowledge to:

- Open Posit Workbench & open a blank R script
- Read a data set into R
- Produce simple data summaries
- Manipulate data sets: transform columns and produce grouped summaries
- Merge data sets

---

class: center, middle

# `R`, RStudio and Posit

---

## Why `R`?

`R` is a programming language designed around statistical analysis. 

--

### Advantages:

- Shareable
- Flexible
- Open Source
- Massive community

--

### Disadvantages:

- Programming is hard

---

## RStudio and Posit

`R` is what does the heavy lifting - think of it as the engine.

RStudio/Posit are the wrappers that allow us to interact with `R` - like the controls of a car.

RStudio and Posit are one and the same, in that Posit used to be called RStudio. At PHS we use a server based version of Posit called [Posit workbench](https://pwb.publichealthscotland.org/auth-sign-in).

---

## Programming

Since `R` is a programming language, it's important to think about tasks from a programming perspective.

The key in this is breaking tasks down into small chunks of what needs to be done. 

Since you are familiar with doing analysis in other software (and to ease you in) we'll start by completing the tasks set out in Excel.

While you are doing this, make a note of the steps you are carrying out while you are doing the analysis.

---

class: center, middle

# Terminology

---

## Getting Started with Posit

To log into Posit Workbench, visit https://pwb.publichealthscotland.org/auth-sign-in and log in with the same credentials you use to log in to your laptop.

Once you have signed in, you will need to set up a session by clicking the New Session button:

INSERT IMAGE

Then select an appropriate number of CPUs and Memory - the default is usually fine unless your are dealing with large amounts of data!

---

## Getting Around the Posit Session

When your session starts there will usually be three panels - one on the left and two on the right:

INSERT IMAGE

You need to first acknowledge the terms and conditions of use by typing in the panel on the left (the console).


Before starting any work in R, you will need to open a script by going to *File > New File > R Script*. Using a script allows you to save your work. 

---

## The Four Panels

INSERT IMAGE

---

## From Excel to R

---

## Vectors

---

## Vector Types

---

## Using Data Frames

---

## Functions

---

class: center, middle

# Manipulating Data

---

## The Tidyverse

---

## Subsetting Columns: `select()`

---

## Subsetting Rows: `filter()`

---

## Summarising Data: `summarise()`

---

## Transforming Data: `mutate()`

---

## Repeating Calculations: `across()`

---

class: center, middle

# Merging data

---

## Binding Rows: `bind_rows()`

---

## Merging Columns (Joins)

---

## Filtering Joins